### ISSUE TITLE
something wrong in local mode

### ISSUE THREAD

**Issue by starshine360** [P-PPPP/JianYingActionsSrt#12]
At the stage of adding media, I found that the folder had been added, rather than a video. How should I do so that it can add videos individually?
![bug](https://user-images.githubusercontent.com/45736998/188933367-85b6a9ff-ee8d-4439-8430-fcb2cf7dd5b1.JPG)

**Comment by P-PPPP** [comment]
Well, The Api is fits for the beta version, seems they has drawback that version(3.3.5beta).
So I will solve this, Never mind and thank u for feedbacking.
i will notice u as soon as the issue fixed :)

**Comment by P-PPPP** [comment]
ok i have figure out..
Basically, the way we add single media isn't change
In jianying, if you wanna add single media, you have to type in the path and filename,then click the background to remove the focus point from filepath bar, then press Enter on your keyboard as i wrote in [Api](https://github.com/P-PPPP/JianYingApi/blob/7333edd9cf4eabfd294b772fcb55cafdc1f1bf80/JianYingApi/Ui_warp.py#L55)
May be the distance i wrote is too close that an bug occurd. i will fix it by change the margin larger.
